export { default as ManageCompany } from "./ManageCompany/ManageCompany"
export { default as ManageJob } from "./ManageJob/ManageJob"
export { default as Report } from "./Report/Report"
export { default as MainPage } from "./MainPage/MainPage"
export { default as CompanyInfo } from "./CompanyInfo/CompanyInfo"
export { default as JobInfo } from "./JobInfo/JobInfo"
